---
include:
  # Nur der Central benötigt den USB-Transport für ZMK Studio.
  - board: nice_nano//zmk
    shield: mwv1_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: mwv1_left

  - board: nice_nano//zmk
    shield: mwv1_right
    artifact-name: mwv1_right

  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset

  # Dieses Minimalabbild prüft BLE und USB ohne Matrix, Split oder Studio.
  - board: nice_nano//zmk
    shield: mwv1_ble_test
    artifact-name: mwv1_ble_test

  # Dieses Abbild protokolliert Matrix- und Tastenereignisse über USB.
  - board: nice_nano//zmk
    shield: mwv1_left
    snippet: zmk-usb-logging
    artifact-name: mwv1_left_debug

  # Dieses Abbild protokolliert die rechte Matrix und Split-Verbindung über USB.
  - board: nice_nano//zmk
    shield: mwv1_right
    snippet: zmk-usb-logging
    artifact-name: mwv1_right_debug
