# Split aktivieren
CONFIG_ZMK_SPLIT=y

# KEIN CONFIG_ZMK_SPLIT_ROLE_CENTRAL hier!
# -> dadurch wird dieses Board automatisch Peripheral

# Split-Kommunikation über BLE
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y

# Keine USB-HID auf der Peripheral-Seite
CONFIG_ZMK_USB=n
