# rechte Hälfte = Peripheral (= Slave)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y

# Bluetooth aktivieren
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y

# Keine USB HID auf der Slave-Seite
CONFIG_ZMK_USB=n
