# Split aktivieren
CONFIG_ZMK_SPLIT=y

# Diese Hälfte ist der Central (Master)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Split-Kommunikation über BLE
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y

# USB nur auf der Central-Seite
CONFIG_ZMK_USB=y
CONFIG_BT_DEVICE_NAME="MWV1 Left"
