# linke Hälfte = Central (= Master)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Bluetooth aktivieren
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y

# USB HID nur auf der Master-Seite
CONFIG_ZMK_USB=y
